CFLAGS= -fPIC -Wall -Werror

all : exercise1a exercise1b

exercise1a : exercise1a.c
	$(CC) -o exercise1a exercise1a.c

exercise1b : exercise1b.c
	$(CC) -o exercise1b exercise1b.c

clean :
	$(RM) exercise1a exercise1b
